// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1hGKhPhtJFo-avs-gfAh3fvtSFIQKJg4',
    appId: '1:167090628177:web:de863215e420714c6fba70',
    messagingSenderId: '167090628177',
    projectId: 'edspert-20',
    authDomain: 'edspert-20.firebaseapp.com',
    storageBucket: 'edspert-20.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCySZCxOhCpjDoOeEek6eF4AmP3G3y7K_4',
    appId: '1:167090628177:android:410b5dbe0c9714316fba70',
    messagingSenderId: '167090628177',
    projectId: 'edspert-20',
    storageBucket: 'edspert-20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ebAHPnm4GxXeyuDxlgO014OTC8wr2X8',
    appId: '1:167090628177:ios:b380e61772689dce6fba70',
    messagingSenderId: '167090628177',
    projectId: 'edspert-20',
    storageBucket: 'edspert-20.appspot.com',
    iosClientId: '167090628177-llsjjl73ilnf31954pth0pk46dro4crf.apps.googleusercontent.com',
    iosBundleId: 'id.finalproject.edspert20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ebAHPnm4GxXeyuDxlgO014OTC8wr2X8',
    appId: '1:167090628177:ios:a185ae1a3ef1089c6fba70',
    messagingSenderId: '167090628177',
    projectId: 'edspert-20',
    storageBucket: 'edspert-20.appspot.com',
    iosClientId: '167090628177-j7hdp8cbmsso7k6jrtvlpdj4u8auj6q7.apps.googleusercontent.com',
    iosBundleId: 'id.finalproject.edspert20.RunnerTests',
  );
}
